default:
    image: registry.smile.fr/magento2/php:8.1-fpm-dev-1
    tags:
        - galaxy-docker-shared
    cache:
        - key: composer-cache
          paths:
              - .composer-cache/
    before_script:
        - composer config -g cache-dir "$(pwd)/.composer-cache"

code-analysis:
    stage: test
    script:
        - composer install --no-interaction
        - composer audit --format=plain
        - vendor/bin/parallel-lint --exclude vendor .
        - vendor/bin/phpcs --extensions=php,phtml
        - vendor/bin/phpcs --extensions=php,phtml --standard=Magento2 --severity=9 --ignore=vendor .
        - vendor/bin/phpstan analyse

phpunit:
    stage: test
    script:
        - mkdir -p .magento
        - cd .magento
        - rm -rf app/code/Smile/Onestock
        - stat composer.json || composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .
        - mkdir -p app/code/Smile/Onestock
        - mv ../* app/code/Smile/Onestock
        - bin/magento module:enable --all
        - bin/magento setup:di:compile
        - vendor/bin/phpunit -c app/code/Smile/Onestock/phpunit.xml --bootstrap "dev/tests/unit/framework/bootstrap.php" --log-junit ../phpunit.xml app/code/Smile/Onestock/Test/Integration
    cache:
        paths:
            - .magento
    artifacts:
        reports:
            junit:
                - phpunit.xml
